const ShopActionTypes =  {
    FETCH_IMAGES_START: 'FETCH_IMAGES_START',
    FETCH_IMAGES_FAILURE: 'FETCH_IMAGES_FAILURE',
    FETCH_IMAGES_SUCCESS: 'FETCH_IMAGES_SUCCESS',
    UPDATE_TOTALS: 'UPDATE_TOTALS',
    UPDATE_START: 'UPDATE_START',
    UPDATE_END: 'UPDATE_END',
    UPDATE_PAGINATION: 'UPDATE_PAGINATION'
}

export default ShopActionTypes;